version: '3'

networks:
  clarive:
    driver: bridge

services:
  db:
    image: mongo:latest
    volumes:
      - ./data/runtime/db:/data/db
      - ./data/dump:/dump
    command: mongod
    networks:
      - clarive
  nginx:
    user: clarive
    image: clarive/clarive:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./logs:/opt/clarive/logs
      - ./config:/opt/clarive/config
      - ./tmp:/opt/clarive/tmp
    networks:
      - clarive
    depends_on: 
      - web
    command: /opt/clarive/local/sbin/nginx -c /opt/clarive/config/nginx.conf
  web:
    user: clarive
    image: clarive/clarive:latest
    restart: always
    volumes:
      - ./logs:/opt/clarive/logs
      - ./jobs:/opt/clarive/jobs
      - ./tmp:/opt/clarive/tmp
      - ./config:/opt/clarive/config
      - ./repo:/opt/clarive/repo
    networks:
      - clarive
    depends_on: 
      - db
    command: /opt/clarive/clarive/bin/cla web-start -c clarive
  disp:
    user: clarive
    image: clarive/clarive:latest
    restart: always
    volumes:
      - ./logs:/opt/clarive/logs
      - ./jobs:/opt/clarive/jobs
      - ./tmp:/opt/clarive/tmp
      - ./config:/opt/clarive/config:ro
      - ./repo:/opt/clarive/repo
    networks:
      - clarive
    depends_on: 
      - db
    command: /opt/clarive/clarive/bin/cla disp-start -c clarive
