version: '2'

networks:
  back:
    driver: bridge

services:
  db:
    image: mongo:latest
    volumes:
      - ./data/runtime/db:/data/db
      - ./data/dump:/dump
    command: mongod --smallfiles
    networks:
      - back
  web:
    image: docker.clarive.com/clarive-web:latest
    environment:
        - CLARIVE_ENV=clarive
    restart: always
    links:
      - db:db
    volumes:
      - ./logs:/opt/clarive/logs
      - ./jobs:/opt/clarive/jobs
      - ./tmp:/opt/clarive/tmp
      - ./config:/opt/clarive/config:ro
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:3000"
    networks:
      - back
  disp:
    image: docker.clarive.com/clarive-disp:latest
    environment:
        - CLARIVE_ENV=clarive
    restart: always
    links:
      - db:db
    volumes:
      - ./logs:/opt/clarive/logs
      - ./jobs:/opt/clarive/jobs
      - ./tmp:/opt/clarive/tmp
      - ./config:/opt/clarive/config:ro
    networks:
      - back
